---
kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: docker.io/nixos/nix
    environment:
      CACHIX_AUTH_TOKEN:
        from_secret: CACHIX_AUTH_TOKEN
    commands:
      - "nix-env -iA nixpkgs.nixFlakes"
      - "echo 'experimental-features = nix-command flakes ca-references' >> /etc/nix/nix.conf"
      - "nix profile install github:NixOS/nixpkgs/nixos-unstable-small#cachix github:NixOS/nixpkgs/nixos-unstable-small#git"
      - "cachix use scratchix"
      - "cachix watch-exec scratchix -- nix flake check -vL"
